### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by tommck** [MikeyBurkman/mdless#1]
Get this error running on any MD file
```
module.js:597
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\tom\AppData\Roaming\npm\node_modules\mdless\node_modules\@patrickkettner\get-cursor-position\index.js:1:74)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

**Comment by MikeyBurkman** [comment]
PRs are welcome

**Comment by jerrygreen** [comment]
If you use [GIT SCM](https://git-scm.com/downloads), then it works. I just tried it: works fine, though I feel lack of table support.
