### ISSUE TITLE
Install Failed with Node 10.9.0 and Yarn 1.9.4 on PopOS (Ubuntu Bionic Beaver)

### ISSUE THREAD

**Issue by dvisztempacct** [MikeyBurkman/mdless#2]
Pops is basically Ubuntu with a System76 PPA and custom installer. Here is my (stock) `sources.list` for proof:

```
# deb cdrom:[Pop_OS 18.04 _Bionic Beaver_ - Release amd64 (20180731)]/ bionic main restricted
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-updates main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-security main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb-src http://us.archive.ubuntu.com/ubuntu/ bionic-backports main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
deb http://apt.pop-os.org/proprietary bionic main
# deb-src http://apt.pop-os.org/proprietary bionic main
```

`node 10.9.0` is installed via `nvm 0.33.11` and `yarn 1.9.4` is installed via `npm 6.2.0`

Now for the actual useful information: what the shell said when I attempted to install:

```
$ yarn global add mdless
yarn global v1.9.4
[1/4] Resolving packages...
warning mdless > node-pager > @patrickkettner/get-cursor-position > node-pre-gyp > hawk > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning mdless > node-pager > @patrickkettner/get-cursor-position > node-pre-gyp > hawk > boom > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
warning mdless > node-pager > @patrickkettner/get-cursor-position > node-pre-gyp > hawk > sntp > hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer
[2/4] Fetching packages...
warning vscode-languageclient@4.0.1: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.9.0 | linux | x64
node-pre-gyp info check checked for "/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node" (not found)
node-pre-gyp http GET https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v64-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @patrickkettner/get-cursor-position@1.0.4 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://github.com/patrickkettner/get-cursor-position/releases/download/1.0.4/pos-v1.0.4-node-v64-linux-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for @patrickkettner/get-cursor-position@1.0.4 and node@10.9.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hdon/.node-gyp/10.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hdon/.node-gyp/10.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hdon/.node-gyp/10.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/hdon/.node-gyp/10.9.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/hdon/.node-gyp/10.9.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/hdon/.node-gyp/10.9.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@10.9.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build'
  CXX(target) Release/obj.target/pos/src/pos.o
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build'
  CXX(target) Release/obj.target/pos/src/pos.o
../src/pos.cc: In function ‘void Method(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/pos.cc:259:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, row, col;
      ^~~
../src/pos.cc: In function ‘void Method(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/pos.cc:259:6: warning: variable ‘ret’ set but not used [-Wunused-but-set-variable]
  int ret, row, col;
      ^~~
  SOLINK_MODULE(target) Release/obj.target/pos.node
sed: can't read ./Release/.deps/Release/obj.target/pos/src/pos.o.d.raw: No such file or directory
rm: cannot remove './Release/.deps/Release/obj.target/pos/src/pos.o.d.raw': No such file or directory
pos.target.mk:99: recipe for target 'Release/obj.target/pos/src/pos.o' failed
make: Leaving directory '/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build'
make: *** [Release/obj.target/pos/src/pos.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-32-generic
gyp ERR! command "/home/hdon/.nvm/versions/node/v10.9.0/bin/node" "/home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node" "--module_name=pos" "--module_path=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release"
gyp ERR! cwd /home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/hdon/.nvm/versions/node/v10.9.0/bin/node /home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node --module_name=pos --module_path=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:961:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
node-pre-gyp ERR! System Linux 4.15.0-32-generic
node-pre-gyp ERR! command "/home/hdon/.nvm/versions/node/v10.9.0/bin/node" "/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position
node-pre-gyp ERR! node -v v10.9.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/home/hdon/.nvm/versions/node/v10.9.0/bin/node /home/hdon/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release/pos.node --module_name=pos --module_path=/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build/Release' (1)
  COPY Release/pos.node
make: Leaving directory '/home/hdon/.config/yarn/global/node_modules/@patrickkettner/get-cursor-position/build'
gyp info ok
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by MikeyBurkman** [comment]
Ack, sorry for the late reply to this.

I updated all the versions of all dependencies to the latest, so maybe it'll work? Unfortunately, the dependency that's failing in the logs above (`@patrickkettner/get-cursor-position`) has not been updated in quite some time, so short of digging into that package (which is a transitive dependency of `node-pager`), or forking node-pager and trying to replace it with another similar library, I'm not sure what to do for that.
